# Generated by Django 4.2.29 on 2026-03-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.TextField()),
                ('login_type', models.CharField(db_index=True, max_length=32)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_logins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(db_index=True, max_length=64)),
                ('api_key', models.TextField()),
                ('secret_key', models.TextField()),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'broker_logins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(max_length=16)),
                ('order_type', models.CharField(max_length=16)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=28)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'demo_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, unique=True)),
                ('password_hash', models.TextField()),
                ('full_name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=180)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_accounts',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='django_orm.useraccount')),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(db_index=True, max_length=32)),
                ('api_key_encrypted', models.TextField()),
                ('secret_key_encrypted', models.TextField()),
                ('api_key_fingerprint', models.CharField(db_index=True, max_length=128)),
                ('label', models.CharField(default='Primary', max_length=64)),
                ('key_hint', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('can_trade', models.BooleanField(default=False)),
                ('can_withdraw', models.BooleanField(default=False)),
                ('permissions_verified', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_accounts', to='django_orm.useraccount')),
            ],
            options={
                'db_table': 'exchange_accounts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailChangeOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.CharField(db_index=True, max_length=180)),
                ('otp_code', models.CharField(max_length=8)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to='django_orm.useraccount')),
            ],
            options={
                'db_table': 'email_change_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ByokOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_account_id', models.BigIntegerField(db_index=True)),
                ('order_id', models.CharField(db_index=True, max_length=128)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(max_length=8)),
                ('order_type', models.CharField(max_length=16)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=28)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('status', models.CharField(max_length=32)),
                ('exchange_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byok_orders', to='django_orm.useraccount')),
            ],
            options={
                'db_table': 'byok_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangeaccount',
            constraint=models.UniqueConstraint(fields=('exchange', 'api_key_fingerprint'), name='uniq_exchange_fingerprint'),
        ),
    ]
