# Generated by Django 3.2.4 on 2026-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0002_demoorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='byokorder',
            name='source',
            field=models.CharField(db_index=True, default='manual', max_length=24),
        ),
        migrations.AddField(
            model_name='exchangeaccount',
            name='live_trading_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangeaccount',
            name='max_order_notional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='tv_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
